### ISSUE TITLE
Please share requirements of the project

### ISSUE THREAD

**Issue by mrghofrani** [LLM360/amber-train#2]
Thanks for this great work and open sourcing it.

I'm trying to execute the training code but due to the lack of requirements, I failed. Could you share the requirements needed for the project? By requirement I mean the version of Python library packages, cuda version, etc.

Thanks,

**Comment by tanyuqian** [comment]
Thanks for noticing LLM360!

We have added [requirements.txt](https://github.com/LLM360/amber-train/blob/main/requirements.txt) for python packages.   Cuda version on our machine is 12.1, but it should be flexible as long as it matches your PyTorch installation.

Please let us know if there are still any problems running this code:)
